pruned unused page components, edited Payment.tsx
nickBarak/goshopping-ui pull request #19
Opened 2020-12-29 22:22 UTC by nickBarak

2020-12-29 23:42 UTC, hishamss requested changes
for some reason, if Stripe library didn't load, the pay button should be disabled

we need to put this back inside the pay button (payment.tsx)
disabled={!stripe}

2020-12-29 23:42 UTC, hishamss commented on src/components/pages/Payment.tsx
> +      <button>Pay</button>
for some reason, if Stripe library didn't load, the pay button should be disabled

we need to put this back inside the pay button 
disabled={!stripe}

2020-12-30 03:41 UTC, nickBarak commented on src/components/pages/Payment.tsx
> +      <button>Pay</button>
I don't see the point of this considering the handleSubmit function already short-circuits if (!stripe || !elements) is true

2020-12-30 04:02 UTC, hishamss commented on src/components/pages/Payment.tsx
> +      <button>Pay</button>
I agree with you

2020-12-30 04:02 UTC, hishamss approved these changes

2020-12-30 04:56 UTC, ZAG852 approved these changes

2020-12-30 04:59 UTC, merged